# Generated by Django 4.2.8 on 2026-03-17 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExtractionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('fields', models.JSONField(default=list, help_text='Lista de campos para extraer datos', verbose_name='Campos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_templates', to='core.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Plantilla de extracción de datos',
                'verbose_name_plural': 'Plantillas de extracción de datos',
            },
        ),
        migrations.CreateModel(
            name='WorkflowPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(choices=[('planning', 'Planificación'), ('search', 'Búsqueda'), ('screening', 'Cribado'), ('eligibility', 'Evaluación de elegibilidad'), ('data_extraction', 'Extracción de datos'), ('quality_assessment', 'Evaluación de calidad'), ('synthesis', 'Síntesis'), ('dissemination', 'Diseminación')], max_length=50, verbose_name='Tipo de fase')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.IntegerField(verbose_name='Orden')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_phases', to='core.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Fase de flujo de trabajo',
                'verbose_name_plural': 'Fases de flujo de trabajo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('total_items', models.IntegerField(default=0, verbose_name='Total de elementos')),
                ('reviewed_items', models.IntegerField(default=0, verbose_name='Elementos revisados')),
                ('included_items', models.IntegerField(default=0, verbose_name='Elementos incluidos')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado en')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tasks', to='workflow.workflowphase', verbose_name='Fase')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tasks', to='core.search', verbose_name='Búsqueda')),
            ],
            options={
                'verbose_name': 'Tarea de cribado',
                'verbose_name_plural': 'Tareas de cribado',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Datos extraídos')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, verbose_name='Extraído en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado en')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('extracted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_data', to=settings.AUTH_USER_MODEL, verbose_name='Extraído por')),
                ('search_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='core.searchresult', verbose_name='Resultado de búsqueda')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.dataextractiontemplate', verbose_name='Plantilla')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_extractions', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Datos extraídos',
                'verbose_name_plural': 'Datos extraídos',
            },
        ),
        migrations.AddIndex(
            model_name='workflowphase',
            index=models.Index(fields=['project', 'is_active'], name='workflow_wo_project_095ba1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowphase',
            unique_together={('project', 'order')},
        ),
        migrations.AddIndex(
            model_name='screeningtask',
            index=models.Index(fields=['reviewer', 'status'], name='workflow_sc_reviewe_8d594c_idx'),
        ),
        migrations.AddIndex(
            model_name='extracteddata',
            index=models.Index(fields=['template', 'is_verified'], name='workflow_ex_templat_d20d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='dataextractiontemplate',
            index=models.Index(fields=['project', 'is_active'], name='workflow_da_project_090c39_idx'),
        ),
    ]
