# Generated by Django 4.2.8 on 2026-03-17 09:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_scholar_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID de Semantic Scholar')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('abstract', models.TextField(blank=True, verbose_name='Resumen')),
                ('authors', models.JSONField(default=list, verbose_name='Autores')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('publication_venue', models.CharField(blank=True, max_length=500, verbose_name='Publicación')),
                ('pdf_url', models.URLField(blank=True, verbose_name='URL del PDF')),
                ('source_url', models.URLField(blank=True, verbose_name='URL de origen')),
                ('citation_count', models.IntegerField(default=0, verbose_name='Número de citas')),
                ('influence_score', models.FloatField(blank=True, null=True, verbose_name='Puntuación de influencia')),
                ('fields_of_study', models.JSONField(default=list, verbose_name='Campos de estudio')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de importación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Datos crudos de API')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-publication_year', '-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('on_hold', 'En pausa'), ('completed', 'Completado')], default='draft', max_length=20, verbose_name='Estado')),
                ('research_question', models.TextField(verbose_name='Pregunta de investigación')),
                ('objectives', models.TextField(verbose_name='Objetivos')),
                ('scope', models.TextField(verbose_name='Alcance')),
                ('protocol_file', models.FileField(blank=True, null=True, upload_to='protocols/', verbose_name='Archivo de protocolo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_projects', to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Falló'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ejecución')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('total_results', models.IntegerField(default=0, verbose_name='Total de resultados')),
                ('processed_results', models.IntegerField(default=0, verbose_name='Resultados procesados')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('search_params', models.JSONField(default=dict, verbose_name='Parámetros de búsqueda')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Posición en resultados')),
                ('relevance_score', models.FloatField(blank=True, null=True, verbose_name='Puntuación de relevancia')),
                ('relevance', models.CharField(choices=[('not_reviewed', 'No revisado'), ('highly_relevant', 'Muy relevante'), ('relevant', 'Relevante'), ('somewhat_relevant', 'Moderadamente relevante'), ('not_relevant', 'No relevante'), ('duplicate', 'Duplicado')], default='not_reviewed', max_length=20, verbose_name='Relevancia')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='Notas del revisor')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='core.article', verbose_name='Artículo')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_results', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.search', verbose_name='Búsqueda')),
            ],
            options={
                'verbose_name': 'Resultado de búsqueda',
                'verbose_name_plural': 'Resultados de búsqueda',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='SearchCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del criterio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('keywords', models.TextField(help_text='Palabras clave separadas por comas', verbose_name='Palabras clave')),
                ('publication_year_from', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año de publicación desde')),
                ('publication_year_to', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año de publicación hasta')),
                ('inclusion_criteria', models.TextField(blank=True, verbose_name='Criterios de inclusión')),
                ('exclusion_criteria', models.TextField(blank=True, verbose_name='Criterios de exclusión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_criteria', to='core.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Criterio de búsqueda',
                'verbose_name_plural': 'Criterios de búsqueda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='search',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='core.searchcriteria', verbose_name='Criterios'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['semantic_scholar_id'], name='core_articl_semanti_f8384e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publication_year'], name='core_articl_publica_57d97d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['citation_count'], name='core_articl_citatio_15869a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['search', 'relevance'], name='core_search_search__1c131a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchresult',
            unique_together={('search', 'article')},
        ),
        migrations.AddIndex(
            model_name='searchcriteria',
            index=models.Index(fields=['project', 'is_active'], name='core_search_project_852ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['criteria', 'status'], name='core_search_criteri_30a334_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['-executed_at'], name='core_search_execute_3f5fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='core_projec_owner_i_56cf8f_idx'),
        ),
    ]
