# Generated by Django 5.2.14 on 2026-05-14 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_openai_only_llm_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('import', 'Importado'), ('vote', 'Voto emitido/cambiado'), ('consensus', 'Cambio de consenso'), ('ai_recommendation', 'Recomendación IA'), ('comment', 'Comentario añadido')], max_length=30, verbose_name='Tipo de evento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Evento de artículo',
                'verbose_name_plural': 'Eventos de artículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='articleaiinteraction',
            new_name='core_articl_project_85d311_idx',
            old_name='core_articl_project_ccf6f0_idx',
        ),
        migrations.RenameIndex(
            model_name='articleaiinteraction',
            new_name='core_articl_article_d95d7c_idx',
            old_name='core_articl_article_bf2f9b_idx',
        ),
        migrations.RenameIndex(
            model_name='articleaiinteraction',
            new_name='core_articl_llm_pro_7180b5_idx',
            old_name='core_articl_llm_pro_99ef78_idx',
        ),
        migrations.RenameIndex(
            model_name='articlediscussionmessage',
            new_name='core_articl_project_02147e_idx',
            old_name='core_articl_project_bd0c24_idx',
        ),
        migrations.RenameIndex(
            model_name='articlediscussionmessage',
            new_name='core_articl_author__21d728_idx',
            old_name='core_articl_author_8fdb01_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmembership',
            new_name='core_projec_project_fc83c5_idx',
            old_name='core_projec_project_6c270f_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmembership',
            new_name='core_projec_user_id_8ed710_idx',
            old_name='core_projec_user_id_c87f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='searchresultassessment',
            new_name='core_search_search__31f7b3_idx',
            old_name='core_search_search__fa1497_idx',
        ),
        migrations.RenameIndex(
            model_name='searchresultassessment',
            new_name='core_search_reviewe_dbecbe_idx',
            old_name='core_search_reviewe_6cb4cf_idx',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_source'], name='core_articl_article_d95c4a_idx'),
        ),
        migrations.AddField(
            model_name='articleevent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.article', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='articleevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_events', to='core.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='articleevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['project', 'article', 'created_at'], name='core_articl_project_0635d5_idx'),
        ),
    ]
